##[>] 🤖🤖
include:
  - project: konradodwrot/cross-repo/misc
    ref: $GRP_KO_VAR_MISC_REF
    file: ci/templates/TriggerAutomation.gitlab-ci.yml

workflow:
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:
  - validate
  - release
  - trigger

default:
  retry:
    max: 2
    when:
      - runner_system_failure
      - api_failure
      - stuck_or_timeout_failure
      - scheduler_failure
      - unknown_failure
  tags:
    - gke-linux-amd64-small

variables:
  ARTIFACT_REGISTRY: $GRP_KO_VAR_ARTIFACT_REGISTRY
  CI_IMAGES_REF: $GRP_KO_VAR_CI_IMAGES_REF
  PROSE_ASSETS_REF: $GRP_KO_VAR_PROSE_ASSETS_REF
  MISC_REF: $GRP_KO_VAR_MISC_REF
  CI_IMAGE: $ARTIFACT_REGISTRY/ci-linux:$CI_IMAGES_REF

validate-pre-commit-all:
  stage: validate
  image: $CI_IMAGE
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - when: on_success
  script:
    - make repo-ci-precommit-all
    - git diff --exit-code HEAD

tag-mint:
  stage: release
  image: $CI_IMAGE
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  variables:
    GIT_DEPTH: "0"
    TAG_TOKEN: $REPO_VAR_TAG_TOKEN
  script:
    - make tag-mint

trigger-automation:
  extends: .TriggerAutomation
  stage: trigger
  rules:
    - if: $CI_COMMIT_TAG =~ /^v[0-9]/
  variables:
    EVENT_TYPE: release.published
    EVENT_DETAILS: '{"producer":"prose-spec","artifact":"cross-repo/prose/spec","tag":"$CI_COMMIT_TAG"}'
##[<] 🤖🤖
