##[>] 🤖🤖
workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:
  - validate

default:
  image: registry.gitlab.com/konradodwrot/infra/oci-images/ci-linux:latest
  tags:
    - gke-linux-amd64

validate-pre-commit-diff:
  stage: validate
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  variables:
    GIT_DEPTH: 0
  script:
    - make repo-ci-precommit-diff
    - git diff --exit-code HEAD

validate-pre-commit-all:
  stage: validate
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: manual
      allow_failure: true
  script:
    - make repo-ci-precommit-all
    - git diff --exit-code HEAD
##[<] 🤖🤖
